# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://ktecv2000.github.io
date_format: "ordinal"
title: TITLE
subtitle: "sub title"
description: "my blog"
keywords: k1, k2, k3
timezone: Asia/Taipei
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: author
organization: organization
organization_url: organization_url
github_username: github_username
location: location
email: email

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: HOME

  -
    href: /categories/
    label: CATEGORIES

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: WIKI

  -
    href: /links/
    label: LINKS

  -
    href: /about/
    label: ABOUT

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: ktecv2000/ktecv2000.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
#disqus:
#    username: 
# https://imsun.net/posts/gitment-introduction/
#gitment:
#    owner: mzlogin
#    repo: blog-comments
#    oauth:
#        client_id: d2e1cbbd298958076462
#        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: ktecv2000
    repo: blog-comments
    clientID: 8ac93d07b0d655a1ef88
    clientSecret: 7382c038df8f05a999bcd1691f500d27398aeb55
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
